language: android
android:
  components:
    - tools
    - build-tools-29.0.2
    - android-29
    - platform-tools
    - extra-android-support # because I'm use support library
    - extra-android-m2repository # because I'm use support library
  licenses:
    - '.+'

sudo: required

jdk:
  - oraclejdk8

install: true

before_script:	
  - chmod +x gradlew	

script:	script:
  - ./gradlew assembleRelease --stacktrace
